#*----------------------------------------------------------------------------*
#* Copyright (C) 2026 ETH Zurich, Switzerland                                 *
#* SPDX-License-Identifier: Apache-2.0                                        *
#*                                                                            *
#* Licensed under the Apache License, Version 2.0 (the "License");            *
#* you may not use this file except in compliance with the License.           *
#* You may obtain a copy of the License at                                    *
#*                                                                            *
#* http://www.apache.org/licenses/LICENSE-2.0                                 *
#*                                                                            *
#* Unless required by applicable law or agreed to in writing, software        *
#* distributed under the License is distributed on an "AS IS" BASIS,          *
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
#* See the License for the specific language governing permissions and        *
#* limitations under the License.                                             *
#*                                                                            *
#* Author:  Marija Zelic                                                      *
#* Author:  Thorir Mar Ingolfsson                                             *
#*----------------------------------------------------------------------------*
# @package _global_
defaults:
  - dataset_types

data_module:
  _target_: data_module.finetune_data_module.FinetuneDataModule
  cfg:
    num_workers: ${num_workers}
    batch_size: ${batch_size}
  train:
    _target_: 'datasets.finetuning_unimodal_datasets_PanLUNA.FinetuningUnimodal_Dataset'
    hdf5_file: "#CHANGEME"
    num_channels: 12 # example for CSN dataset, change accordingly
    channels: ${dataset_types.csn.channels} # example
    location_fn: ${dataset_types.csn.location_fn}
    sensor_type: ${dataset_types.csn.sensor_type}
  val:
    _target_: 'datasets.finetuning_unimodal_datasets_PanLUNA.FinetuningUnimodal_Dataset'
    hdf5_file: "#CHANGEME"
    num_channels: 12
    channels: ${dataset_types.csn.channels}
    location_fn: ${dataset_types.csn.location_fn}
    sensor_type: ${dataset_types.csn.sensor_type}
  test: 
    _target_: 'datasets.finetuning_unimodal_datasets_PanLUNA.FinetuningUnimodal_Dataset'
    hdf5_file: "#CHANGEME"
    num_channels: 12
    channels: ${dataset_types.csn.channels}
    location_fn: ${dataset_types.csn.location_fn}
    sensor_type: ${dataset_types.csn.sensor_type}
