# @package _global_ 
#*----------------------------------------------------------------------------*
#* Copyright (C) 2025 ETH Zurich, Switzerland                                 *
#* SPDX-License-Identifier: Apache-2.0                                        *
#*                                                                            *
#* Licensed under the Apache License, Version 2.0 (the "License");            *
#* you may not use this file except in compliance with the License.           *
#* You may obtain a copy of the License at                                    *
#*                                                                            *
#* http://www.apache.org/licenses/LICENSE-2.0                                 *
#*                                                                            *
#* Unless required by applicable law or agreed to in writing, software        *
#* distributed under the License is distributed on an "AS IS" BASIS,          *
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
#* See the License for the specific language governing permissions and        *
#* limitations under the License.                                             *
#*                                                                            *
#* Author:  Danaé Broustail                                                   *
#* Author:  Thorir Mar Ingolfsson                                             *
#*----------------------------------------------------------------------------*
model:
  _target_: models.LuMamba.LuMamba
  # ---- shared parameters between luna and femba
  num_classes: 0 # Change for corresponding finetuning dataset
  # ---- luna parameters
  patch_size: 40
  num_queries: 6
  embed_dim: 64
  num_heads: 2
  mlp_ratio: 4.
  drop_path: 0.0
  # ---- femba parameters
  exp: 2 # dimension expansion factor inside Mamba block
  num_blocks: 2 # number of Mamba blocks
  bidirectional_strategy: "add" # strategy for bidirectional communication between the two branches, options: "add" or "ew_multiply"
